title: build-your-own-weather-station
hero_image: images/banner.png
description: build-your-own-weather-station description
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 3 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: developer
interests: "nature/outside/weather, physical computing"
technologies: "electronics, physical computing, python"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Humidity & temperature
  - title: Air Quality
  - title: Active mechanical sensors
  - title: Wind speed
  - title: Wind gusts
  - title: Wind direction
  - title: Rainfall
  - title: Fully functional weather station
  - title: Assembling everything ready for outdoors
  - title: Challenge: Add custom sensors
